### ISSUE TITLE
State Sync fails on umeemania-1 w/ umeed-v2.0.3-rc2 on Apple Silicon M1 (arm)

### ISSUE THREAD

**Issue by dreamcodez** [umee-network/umee#1077]
## Summary of Bug

State Sync fails on umeemania-1 w/ umeed-v2.0.3-rc2 on Apple Silicon M1 (arm)

## Version

Please provide the output of the following commands:

- `$ umeed version` : umeed-v2.0.3-rc2
- `$ go version` : N/A built from ci
- `$ uname -a` : Darwin deserteagle.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

## Steps to Reproduce

1. setup statesync against umeemania-1 with these witness servers and settings:
```
[statesync]
enable = true
rpc_servers = "https://rpc.alley.umeemania-1.network.umee.cc:443,https://rpc.festival.umeemania-1.network.umee.cc:443"
trust_height = 1210000
trust_hash = "089D9DB7AC8A38BCEA9EAB6C3E076CDA22B81B3026C30472FC23612B117F116F"
trust_period = "3000h"
```
2. setup persistent peers:
```
persistent_peers = "67cd50cac0eff503a7c9efd537d369cc7a3ebe96@34.83.162.159:26656,08f30f7119ae1317082d50fac6a08e6f2400126f@34.83.251.68:26656"
```
3. wait until you get a LastAppHash failure (~30 mins)
----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by brianosaurus** [comment]
```10:16AM INF commit synced commit=436F6D6D697449447B5B323236203834203238203936203133362032353520353820362035392038392031343020313330203733203134362032323120313236203139392031333020313730203838203135362032382033392031333620313130203134392031372031353820333620313935203535203137325D3A3132374446437D
10:16AM INF committed state app_hash=E2541C6088FF3A063B598C824992DD7EC782AA589C1C27886E95119E24C337AC height=1211900 module=state num_txs=1
10:16AM INF Fast Sync Rate blocks/s=6.287607404569742 height=1211900 max_peer_height=1216217 module=blockchain
panic: failed to process committed block (1211901:625D9A3842F6A13AE97C2F4FFAF12569757CAB9D3D417A2B7EE0E0BE7CB21980): wrong Block.Header.LastResultsHash.  Expected 4DC8EAC516E66DA11D91B422061F449467040FF528E65806A848CBAA045110C0, got C1ECA3658BB19FD9BCAD17C80AE68E1A6E3A546591499A0A8790C24EC0CC3AA5 [recovered]
	panic: failed to process committed block (1211901:625D9A3842F6A13AE97C2F4FFAF12569757CAB9D3D417A2B7EE0E0BE7CB21980): wrong Block.Header.LastResultsHash.  Expected 4DC8EAC516E66DA11D91B422061F449467040FF528E65806A848CBAA045110C0, got C1ECA3658BB19FD9BCAD17C80AE68E1A6E3A546591499A0A8790C24EC0CC3AA5
last events:
0: scBlockReceived{1211907#2E5C6ECF690901CE4FB8A0F8C6750C4F9EE20252C9B392E809BF94252EB32965 from 08f30f7119ae1317082d50fac6a08e6f2400126f}
1: scBlockReceived{1211897#D6D2D26DD75247FEF129D26C340784787A12871B358000803D3E865587E90B48 from 244d611c2ee9a0a00a1c88b55e439fca661d8875}
2: scBlockReceived{1211898#C960483B5A20814860C9DF36934C3EBE9513DCE5F52B7F748F4D098BA7510839 from 08f30f7119ae1317082d50fac6a08e6f2400126f}
3: scBlockReceived{1211899#05F8F4A7BF53940F4DC1C754B663D9C82D8AF94B2379EAE64AC6EB440DCFB199 from 0eb962508b9d82629005142fc8aed7e3f225c3d3}
4: scBlockReceived{1211900#3C8B1CD32529C67AB3EDBCD0432AB0A9BE5EBEAAE853BACC902001B5575D19C1 from 08f30f7119ae1317082d50fac6a08e6f2400126f}
5: scBlockReceived{1211901#625D9A3842F6A13AE97C2F4FFAF12569757CAB9D3D417A2B7EE0E0BE7CB21980 from 0eb962508b9d82629005142fc8aed7e3f225c3d3}
6: scBlockReceived{1211902#A924D3FEE173FD0868F8C3F0452E426E92ABDE095715F459AC18AA9FE81475D5 from 08f30f7119ae1317082d50fac6a08e6f2400126f}
7: scBlockReceived{1211890#22C0642FD9E7D49D70AF6AC6AF2CF0AF55E2531DC345E8E9BDA7294178FA9FC8 from 08f30f7119ae1317082d50fac6a08e6f2400126f}
8: scBlockReceived{1211892#7D27AC5EA5B24A43CE61842AC81F05BD064EE45C371AD7F699BE6AE030B3058C from 08f30f7119ae1317082d50fac6a08e6f2400126f}
9: scBlockReceived{1211891#1E0ABF19E1A7A800FEDE070AE6E7BC4E6B3E842FE789491FB3378C598B41F5D5 from 0eb962508b9d82629005142fc8aed7e3f225c3d3}
10: scBlockReceived{1211893#508FA219EB7A65425DA02453A6EC4A3475EBEECF0229452EA1720B76F09CD4F2 from 244d611c2ee9a0a00a1c88b55e439fca661d8875}
11: scBlockReceived{1211895#91C24DCB5A307252FE6B25B02CF86635A6CB9AA47CBF060526F7A0CA463210F6 from 0eb962508b9d82629005142fc8aed7e3f225c3d3}
12: scBlockReceived{1211896#3B8F9BFE30FE71392BF4F61A1C06687D2E25B52FD6F365B3F813DEE07C0828F4 from 08f30f7119ae1317082d50fac6a08e6f2400126f}
13: scBlockReceived{1211894#D7ED4E7C4636E8E2EA245C24B38E9BCD6CB7D3CA8AD1B20384C33107F09644ED from 08f30f7119ae1317082d50fac6a08e6f2400126f}
14: scBlockReceived{1211884#6A21358880914CFFCAFCEC1BB29D7BFE3598AA9B2F1E0977C20D5C99E9267767 from 0eb962508b9d82629005142fc8aed7e3f225c3d3}
15: scBlockReceived{1211885#AEC73034442CA76EC9161FA80E5A27570C56D4ED3FB569FCA09995C2786C9F1D from 08f30f7119ae1317082d50fac6a08e6f2400126f}
16: scBlockReceived{1211887#F9D924923C254733C3071FFEB3881EDE73DA417FA672D1C8D02B3388CB3FA3B8 from 08f30f7119ae1317082d50fac6a08e6f2400126f}
17: scBlockReceived{1211886#BAD7028706520C2F8EF8F8B3498AEE3BED567EEAE714D2AFAE411D9B41A7E75A from 244d611c2ee9a0a00a1c88b55e439fca661d8875}
18: scBlockReceived{1211889#C00508C9823F82B4BA8A2D718E8EA697E692B9626F1610B7E34DFE06314BD065 from 4074c562a9e65312827987c77e49047697e6d60e}
19: scBlockReceived{1211883#E5476918BCB21A5CBCC79F308AEB514803F68A8C56B469A48A9CBF558AC264BE from 08f30f7119ae1317082d50fac6a08e6f2400126f}
20: scBlockReceived{1211888#C54BE255D54D2A873444CCDF1C8E6F6D3A4439AC68E3E7CEBF3303B8AF62339B from 0eb962508b9d82629005142fc8aed7e3f225c3d3}
21: scBlockReceived{1211877#3DE9B0B0B9942941FCCBFD534B0E4833767121BDEB84855870EA7D7772C63457 from 0eb962508b9d82629005142fc8aed7e3f225c3d3}
22: scBlockReceived{1211878#A4F5E7E410D7B712C4A8E7CA4BD18120EBE78B405A2EF8059E7BE5B7106CC78B from 08f30f7119ae1317082d50fac6a08e6f2400126f}
23: scBlockReceived{1211879#EE92BE96CFDF4BC87FAB3E6B2B54217198D6111641CBC49E6640DDE0D7ACF6BB from 244d611c2ee9a0a00a1c88b55e439fca661d8875}
24: scBlockReceived{1211880#F34D38954CCFC4F3895206837F4F5B2568D76B0EC5B613586B34FD003F792FE6 from 08f30f7119ae1317082d50fac6a08e6f2400126f}


goroutine 448 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start.func1()
	github.com/tendermint/tendermint@v0.34.19/blockchain/v2/routine.go:77 +0x234
panic({0x106a48ce0, 0x1406090e9e0})
	runtime/panic.go:838 +0x204
github.com/tendermint/tendermint/blockchain/v2.(*pcState).handle(0x140005f0060, {0x106d4b5f8?, 0x107c4cbc0?})
	github.com/tendermint/tendermint@v0.34.19/blockchain/v2/processor.go:182 +0x704
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0x140011c4540)
	github.com/tendermint/tendermint@v0.34.19/blockchain/v2/routine.go:94 +0x204
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).startSync
	github.com/tendermint/tendermint@v0.34.19/blockchain/v2/reactor.go:152 +0x15c
[1]  + exit 2     nohup umeed-v2.0.3-rc2 start &>> umeed.log```

**Comment by robert-zaremba** [comment]
duplicates  #826
