### ISSUE TITLE
Revert historacle proto changes to x/oracle Params struct

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1575]
Current `main` branch causes a panic when continuing from `umee-1` (mainnet) state. It is looking for oracle params which do not exist in state.

Recommended fix: remove new fields from `.proto`, then `make proto-all` and push to `main`.

Required before next release candidate.

New params will need a migration when we wish to deploy it to mainnet.

**Comment by toteki** [comment]
```
panic: UnmarshalJSON cannot decode empty bytes

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x102c217b0, 0xc0002d59a0}, 0xc000296948, {0x102bf5d50, 0xc0015d0de0}, {0x102bf5da0, 0xc0015d0ed0}, {0xc00025bbc0, 0x6, 0x1e}, ...}, ...)
	/Users/zeta/go/pkg/mod/github.com/umee-network/cosmos-sdk@v0.46.4-umee/x/params/types/subspace.go:110 +0x30e
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.GetParamSet({{0x102c217b0, 0xc0002d59a0}, 0xc000296948, {0x102bf5d50, 0xc0015d0de0}, {0x102bf5da0, 0xc0015d0ed0}, {0xc00025bbc0, 0x6, 0x1e}, ...}, ...)
	/Users/zeta/go/pkg/mod/github.com/umee-network/cosmos-sdk@v0.46.4-umee/x/params/types/subspace.go:239 +0x12a
github.com/umee-network/umee/v3/x/oracle/keeper.Keeper.GetParams(...)
	/Users/zeta/desktop/umee/x/oracle/keeper/params.go:109
github.com/umee-network/umee/v3/x/oracle.EndBlocker({{0x102c10750, 0xc00019c008}, {0x102c237c0, 0xc0061f5a40}, {{0xb, 0x0}, {0xc005311a20, 0x6}, 0x3a22d8, {0x1bec32ad, ...}, ...}, ...}, ...)
	/Users/zeta/desktop/umee/x/oracle/abci.go:22 +0x168
github.com/umee-network/umee/v3/x/oracle.AppModule.EndBlock(...)
	/Users/zeta/desktop/umee/x/oracle/module.go:182
github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x102c10750, 0xc00019c008}, {0x102c237c0, 0xc0061f5a40}, {{0xb, 0x0}, {0xc005311a20, 0x6}, 0x3a22d8, ...}, ...}, ...)
	/Users/zeta/go/pkg/mod/github.com/umee-network/cosmos-sdk@v0.46.4-umee/types/module/module.go:505 +0x482
github.com/umee-network/umee/v3/app.(*UmeeApp).EndBlocker(_, {{0x102c10750, 0xc00019c008}, {0x102c237c0, 0xc0061f5a40}, {{0xb, 0x0}, {0xc005311a20, 0x6}, 0x3a22d8, ...}, ...}, ...)
	/Users/zeta/desktop/umee/app/app.go:799 +0x78
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc000df9340, {0x0?})
	/Users/zeta/go/pkg/mod/github.com/umee-network/cosmos-sdk@v0.46.4-umee/baseapp/abci.go:206 +0x165
github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc0000bdaa0, {0xc0000bdaa0?})
	/Users/zeta/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/abci/client/local_client.go:288 +0xdf
github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc0022968a0?, {0xc0002b81c0?})
	/Users/zeta/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/proxy/app_conn.go:89 +0x24
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x102c11940?, 0xc001845320}, {0x102c1a4f0, 0xc0013815c0}, 0xc000e9ad20, {0x102c22bb0, 0xc002df2240}, 0x3a22d7?)
	/Users/zeta/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/state/execution.go:327 +0x55f
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0017ae2d0, 0x8}}, {0xc0017ae2d8, 0x6}, 0x1, 0x3a22d7, {{0xc00b97c040, ...}, ...}, ...}, ...)
	/Users/zeta/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc0017ae2d0, 0x8}}, {0xc0017ae2d8, 0x6}, 0x1, 0x3a22d7, {{0xc00b97c040, ...}, ...}, ...}, ...)
	/Users/zeta/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc0017ae2d0, 0x8}}, {0xc0017ae2d8, 0x6}, 0x1, 0x3a22d7, {{0xc00b97c040, ...}, ...}, ...}, ...)
	/Users/zeta/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc002bd1940, {0x102c24960, 0xc000525380})
	/Users/zeta/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc0017ae2d0, 0x8}}, {0xc0017ae2d8, 0x6}, 0x1, 0x3a22d7, ...}, ...)
	/Users/zeta/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/node/node.go:330 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0001488c0, {0x102c0b7c0, 0xc0011bf540}, 0xc0015e25b0, {0x102bedda0, 0xc001db12c0}, 0x1?, 0x0?, 0xc0015e27e0, {0x102c11940, ...}, ...)
	/Users/zeta/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/node/node.go:778 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x102c323e0, 0xc001244270}, 0x0, {0xc001240430, 0x6}, {0x102c28878, ...}, ...}, ...)
	/Users/zeta/go/pkg/mod/github.com/umee-network/cosmos-sdk@v0.46.4-umee/server/start.go:313 +0x7fb
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00100e600?, {0xc000e3ea40?, 0x0?, 0x2?})
	/Users/zeta/go/pkg/mod/github.com/umee-network/cosmos-sdk@v0.46.4-umee/server/start.go:143 +0x148
github.com/spf13/cobra.(*Command).execute(0xc00100e600, {0xc000e3ea20, 0x2, 0x2})
	/Users/zeta/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000fbe600)
	/Users/zeta/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/zeta/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/zeta/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x102101bf0?, {0xc001085a80, 0x4}, {0xc0001553c8, 0x11})
	/Users/zeta/go/pkg/mod/github.com/umee-network/cosmos-sdk@v0.46.4-umee/server/cmd/execute.go:36 +0x20f
main.main()
	/Users/zeta/desktop/umee/cmd/umeed/main.go:16 +0x4d
```

**Comment by robert-zaremba** [comment]
Experimental flag won't work here.

Thanks @toteki for checking this.
Instead of reverting, let's add a migration. I can handle that.
