### ISSUE TITLE
x/leverage: consensus failure

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#650]
```
Mar 15 13:57:16 resistability umeed-beta-v0.8.6[27594]: 1:57PM ERR CONSENSUS FAILURE!!! err="8ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2,0uumee: invalid coins" module=consensus stack="goroutine 116 [running]:
runtime/debug.Stack()
	/usr/local/src/runtime/debug/stack.go:24 +0x65
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:726 +0x4c
panic({0x1b948e0, 0xc030fdff20})
	/usr/local/src/runtime/panic.go:1038 +0x215
github.com/umee-network/umee/x/leverage.EndBlocker({{0x224cce8, 0xc000052050}, {0x227b7e0, 0xc012127d00}, {{0xb, 0x0}, {0xc034379f38, 0x12}, 0x12e7b, {0x2538f513, ...}, ...}, ...}, ...)
	/tmp/build/umee/x/leverage/abci.go:17 +0x145
github.com/umee-network/umee/x/leverage.AppModule.EndBlock(...)
	/tmp/build/umee/x/leverage/module.go:174
github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x224cce8, 0xc000052050}, {0x227b7e0, 0xc012127d00}, {{0xb, 0x0}, {0xc034379f38, 0x12}, 0x12e7b, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/types/module/module.go:495 +0x33d
github.com/umee-network/umee/app/beta.(*UmeeApp).EndBlocker(...)
	/tmp/build/umee/app/beta/app.go:639
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc00103f860, {0x100000000000020})
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/baseapp/abci.go:211 +0x25d
github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000ee6840, {0xc000ee6840})
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:288 +0xdf
github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc024e95fa0, {0x20})
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:89 +0x24
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x224da78, 0xc000f02d20}, {0x2263f80, 0xc000c7e4a0}, 0xc00bb32d20, {0x2273bf8, 0xc000d191a0}, 0x12e7a)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/state/execution.go:327 +0x54e
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc000d86540, 0x8}}, {0xc0010c7008, 0x12}, 0x1, 0x12e7a, {{0xc01fd1aec0, ...}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000f7ae00, 0x12e7b)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1635 +0x9fd
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000f7ae00, 0x12e7b)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1546 +0x305
github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1481 +0x87
github.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc000f7ae00, 0x12e7b, 0x0)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1519 +0xc06
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc000f7ae00, 0xc02e5bf540, {0xc001413e30, 0x28})
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:2132 +0xb6e
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000f7ae00, 0xc02e5bf540, {0xc001413e30, 0xc010f48200})
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1930 +0x2c
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000f7ae00, {{0x22060a0, 0xc015c10498}, {0xc001413e30, 0x0}})
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:838 +0x40b
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000f7ae00, 0x0)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:762 +0x419
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/state.go:378 +0x12f
```

**Comment by alexanderbez** [comment]
Issue seems to stem from `AccrueAllInterest`.

**Comment by alexanderbez** [comment]
My guess is it's probably coming from any number of the `NewCoin` calls, which internally calls `Validate`, which would error if zero.

My suggestion is to add zero balance checks prior to any `NewCoin` call.
